# هذه هي منصات التمويل المدعومة

github: # اسم المستخدم الخاص بك
patreon: # اسم المستخدم الخاص بك
open_collective: # اسم المشروع الخاص بك
ko_fi: # اسم المستخدم الخاص بك
tidelift: # npm/اسم الحزمة
community_bridge: # اسم المشروع الخاص بك
liberapay: # اسم المستخدم الخاص بك
issuehunt: # اسم المستخدم الخاص بك
otechie: # اسم المستخدم الخاص بك
lfx_crowdfunding: # اسم المشروع الخاص بك
custom: # رابط مخصص أو مصفوفة من الروابط