blank_issues_enabled: false
contact_links:
  - name: أسئلة المجتمع
    url: https://github.com/yourusername/internal-linking-analyzer-pro/discussions
    about: يرجى طرح الأسئلة العامة والمناقشات هنا.