name: Mark stale issues and pull requests

on:
  schedule:
    - cron: '30 1 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
      - uses: actions/stale@v10
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: 'هذه المشكلة قديمة بسبب عدم النشاط. ستغلق تلقائيًا إذا لم يكن هناك نشاط إضافي.'
          stale-pr-message: 'طلب السحب هذا قديم بسبب عدم النشاط. سيغلق تلقائيًا إذا لم يكن هناك نشاط إضافي.'
          close-issue-message: 'تم إغلاق هذه المشكلة تلقائيًا بسبب عدم النشاط.'
          close-pr-message: 'تم إغلاق طلب السحب هذا تلقائيًا بسبب عدم النشاط.'
          days-before-stale: 60
          days-before-close: 7
          stale-issue-label: 'stale'
          stale-pr-label: 'stale'
          exempt-issue-labels: 'pinned,security,enhancement,bug'
          exempt-pr-labels: 'pinned,security,work-in-progress'
          exempt-all-milestones: true
          operations-per-run: 100